python3 2_sub.manhattanPlot.py /home/iHiO10009/yuching/data/1.QC_GWAS_v2/impute2_keepFinalBC65yoControls_updatedSex_logistic_assoc_v2.assoc.logistic Breast_cancers /home/iHiO10009/yuching/data/1.QC_GWAS_v2/breastCancer_65yoControls_manPlot.png

python3 2_sub.manhattanPlot.py /home/iHiO10009/yuching/data/1.QC_GWAS_v2/impute2_keepFinalBCControls_updatedSex_logistic_assoc_v2.assoc.logistic Breast_cancers /home/iHiO10009/yuching/data/1.QC_GWAS_v2/breastCancer_matchAgeControls_manPlot.png
